openapi: 3.1.0
info:
  title: Weather Forecast
  description: |-
    This is a formal description of the Weather Forecast sample APIs for
    the AspNetCore Web API template, or a variant thereof.
  version: 2.0
servers:
  - url: https://localhost:7024/api/v2
paths:
  /Forecast:
    get:
      tags:
        - forecast
      summary: Get Weather Forecast
      description: Gets the current weather forecast.
      operationId: getForecast
      responses:
        "200":
          description: The current forecast for weather.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Forecast"
components:
  schemas:
    Forecast:
      type: object
      additionalProperties: false
      properties:
        date:
          type: string
          format: date
        temperatureK:
          type: integer
          format: int32
        summary:
          $ref: "#/components/schemas/WeatherSummary"
      required: [date, temperatureK, summary]
    WeatherSummary:
      type: string
      enum:
        - Freezing
        - Bracing
        - Chilly
        - Cool
        - Mild
        - Warm
        - Balmy
        - Hot
        - Sweltering
        - Scorching
